// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVg16I6rvoz864lRmZHRjOIwo0txRotX0',
    appId: '1:796626637593:web:6fffa9ed2707e82451eb88',
    messagingSenderId: '796626637593',
    projectId: 'jarnama-app-89238',
    authDomain: 'jarnama-app-89238.firebaseapp.com',
    storageBucket: 'jarnama-app-89238.appspot.com',
    measurementId: 'G-MTP8E1JNYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZ7909f64Rnz0A6vhxwY74J_5Yyd4eyo',
    appId: '1:796626637593:android:ad6a7bc71a30fc1551eb88',
    messagingSenderId: '796626637593',
    projectId: 'jarnama-app-89238',
    storageBucket: 'jarnama-app-89238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4V4bPZhfi-ZajXMOT5G2qZMoPJMm8kPc',
    appId: '1:796626637593:ios:8a46fbd00ab0a5fa51eb88',
    messagingSenderId: '796626637593',
    projectId: 'jarnama-app-89238',
    storageBucket: 'jarnama-app-89238.appspot.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4V4bPZhfi-ZajXMOT5G2qZMoPJMm8kPc',
    appId: '1:796626637593:ios:00d31f80ab153d5c51eb88',
    messagingSenderId: '796626637593',
    projectId: 'jarnama-app-89238',
    storageBucket: 'jarnama-app-89238.appspot.com',
    iosBundleId: 'com.example.jarnamaApp.RunnerTests',
  );
}
